# sds visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
gems: ['kramdown','jekyll-paginate']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
#markdown: redcarpet	
exclude: ["vendor"]

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Udi Cohen's blog

description: Udi Cohen's blog
author:
  name: Udi Cohen
  email: 
  github: udinic  
  twitter: udinic
  linkedin: udinic
  gplus: +UdiCohen
  bio: My adventures 
  email_md5: 107169775092a3ef4ae94fad5695613a

disqus_short_name: udinic-blog
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
permalink: /:year/:month/:day/:title/
url: http://blog.udinic.com/
BASE_PATH:
